version: '3.7'

# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-airflow-environment: &x_airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__FERNET_KEY=hCRoPUYBO27QiEg1MRu5hSjLG7yNd8y8XKlm-8kRlkQ=
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=10
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
  - AIRFLOW__WEBSERVER__AUTHENTICATE=False
  - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080/airflow
  - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
  - AIRFLOW__WEBSERVER__PROXY_FIX_X_FOR=1
  - AIRFLOW__WEBSERVER__PROXY_FIX_X_HOST=3

# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/index.html:/var/www/default/index.html
    networks:
      - tfx-cb-network

  jupyterlab:
#    image: tfx-cb-jupyter:0.0.1
    image: europe-west1-docker.pkg.dev/tfx-training-329508/tfx/tfx-cb-jupyter
    # The webserver initializes permissions, so sleep for that to (approximately) be finished
    # No disaster if the webserver isn't finished by then, but create_user will start spitting out errors until the permissions exist
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ./dags:/home/tfx/dags
      - ./data:/home/tfx/data
      - ./tfx:/home/tfx/tfx       # for observing
      - ./tfx:/opt/airflow/tfx    # for consistent artefacts' lookup via MLMD
      - ./notebooks:/home/tfx/notebooks
      - ./logs:/opt/airflow/logs:rw
    networks:
      - tfx-cb-network

  webserver:
    image:  europe-west1-docker.pkg.dev/tfx-training-329508/tfx/tfx-cb-airflow
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./logs:/opt/airflow/logs:rw
    ports:
      - "8181:8080"
    environment: *x_airflow_environment
    command: webserver
    networks:
      - tfx-cb-network

  scheduler:
    image: europe-west1-docker.pkg.dev/tfx-training-329508/tfx/tfx-cb-airflow
    restart: always
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ./dags:/opt/airflow/dags:rw
      - ./data:/opt/airflow/data:rw
      - ./tfx:/opt/airflow/tfx:rw
      - ./logs:/opt/airflow/logs:rw
    environment: *x_airflow_environment
    entrypoint: ["/bin/bash"]
    command: ["-c", "airflow scheduler"]
    networks:
      - tfx-cb-network

  init:
    image: europe-west1-docker.pkg.dev/tfx-training-329508/tfx/tfx-cb-airflow
    depends_on:
      - postgres
    environment: *x_airflow_environment
    entrypoint: /bin/bash
    # The webserver initializes permissions, so sleep for that to (approximately) be finished
    # No disaster if the webserver isn't finished by then, but create_user will start spitting out errors until the permissions exist
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
    networks:
      - tfx-cb-network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    networks:
      - tfx-cb-network

networks:
  tfx-cb-network:
